-- ==========================================================================
-- 0014 - the November 2023 run sheets: the weekly pattern
--
-- Generated by data/build_nov23_import.py from the two spreadsheets in data/.
-- Do not hand-edit: change the sheet or the generator and regenerate.
--
-- What the sheets DO say, and is therefore reliable here:
--   the customer list, addresses, what to collect or deliver, access notes
--   and contacts, which weekdays each customer is visited, and whether they
--   are weekly, fortnightly, monthly or on call.
--
-- What the sheets do NOT say, and is a guess for the office to correct:
--
--   * WHICH DRIVER. Split by suburb: the west on Kemu's van, the city and
--     inner east and south on Darren's, Werribee and Wyndham on Keith's,
--     Geelong on the truck. Nothing in the sheet supports this beyond
--     geography. Moving a customer to another run is remove-then-add in the
--     Runs screen, so expect that to be the bulk of the tidying up.
--
--   * THE ORDER WITHIN A DAY. Alphabetical, because the master sheet is
--     alphabetical. The one exception is Kemu's Thursday, whose real running
--     order came off his own sheet and is already loaded - left untouched,
--     with the master sheet's extra Thursday stops appended behind it.
--
-- Re-runnable. Customers match on external_ref; stops are skipped when the
-- same customer already sits on that run and weekday.
-- ==========================================================================

-- -- the weekly pattern -----------------------------------------------------
-- Kemu's Thursday closing marker moves to the back so his proven running
-- order survives the extra Thursday stops the master sheet adds behind it.
update public.route_stops set seq = 900
 where route_id = '353c2c0e-4dd6-4fbd-bbc4-7c797bf625c6' and weekday = 4 and kind = 'target' and seq < 900;

insert into public.route_stops (business_id, route_id, customer_id, kind, tickable,
       weekday, visit_no, seq, frequency, anchor_date, nth_of_month)
select 'b7d18d8b-aa7c-4dd8-a37a-4ced75748239', v.route_id::uuid, c.id, 'customer', true,
       v.weekday, 1, v.seq, v.frequency,
       -- the snap_fortnightly_anchor trigger moves this to the stop's own weekday
       case when v.frequency = 'fortnightly' then current_date end,
       v.nth_of_month
  from (values
  -- Van (Kemu) - the west, Mon (15)
  ('NOV23-004', '353c2c0e-4dd6-4fbd-bbc4-7c797bf625c6', 1, 10, 'on_call', null),
  ('NOV23-006', '353c2c0e-4dd6-4fbd-bbc4-7c797bf625c6', 1, 20, 'weekly', null),
  ('C-002', '353c2c0e-4dd6-4fbd-bbc4-7c797bf625c6', 1, 30, 'weekly', null),
  ('NOV23-009', '353c2c0e-4dd6-4fbd-bbc4-7c797bf625c6', 1, 40, 'on_call', null),
  ('NOV23-012', '353c2c0e-4dd6-4fbd-bbc4-7c797bf625c6', 1, 50, 'weekly', null),
  ('C-009', '353c2c0e-4dd6-4fbd-bbc4-7c797bf625c6', 1, 60, 'weekly', null),
  ('NOV23-034', '353c2c0e-4dd6-4fbd-bbc4-7c797bf625c6', 1, 70, 'on_call', null),
  ('NOV23-042', '353c2c0e-4dd6-4fbd-bbc4-7c797bf625c6', 1, 80, 'weekly', null),
  ('NOV23-053', '353c2c0e-4dd6-4fbd-bbc4-7c797bf625c6', 1, 90, 'weekly', null),
  ('C-006', '353c2c0e-4dd6-4fbd-bbc4-7c797bf625c6', 1, 100, 'weekly', null),
  ('NOV23-062', '353c2c0e-4dd6-4fbd-bbc4-7c797bf625c6', 1, 110, 'weekly', null),
  ('NOV23-072', '353c2c0e-4dd6-4fbd-bbc4-7c797bf625c6', 1, 120, 'weekly', null),
  ('C-001', '353c2c0e-4dd6-4fbd-bbc4-7c797bf625c6', 1, 130, 'weekly', null),
  ('C-005', '353c2c0e-4dd6-4fbd-bbc4-7c797bf625c6', 1, 140, 'weekly', null),
  ('NOV23-076', '353c2c0e-4dd6-4fbd-bbc4-7c797bf625c6', 1, 150, 'on_call', null),
  -- Van (Kemu) - the west, Tue (4)
  ('C-003', '353c2c0e-4dd6-4fbd-bbc4-7c797bf625c6', 2, 10, 'weekly', null),
  ('NOV23-030', '353c2c0e-4dd6-4fbd-bbc4-7c797bf625c6', 2, 20, 'weekly', null),
  ('NOV23-041', '353c2c0e-4dd6-4fbd-bbc4-7c797bf625c6', 2, 30, 'weekly', null),
  ('NOV23-062', '353c2c0e-4dd6-4fbd-bbc4-7c797bf625c6', 2, 40, 'weekly', null),
  -- Van (Kemu) - the west, Wed (4)
  ('NOV23-002', '353c2c0e-4dd6-4fbd-bbc4-7c797bf625c6', 3, 10, 'weekly', null),
  ('NOV23-006', '353c2c0e-4dd6-4fbd-bbc4-7c797bf625c6', 3, 20, 'weekly', null),
  ('NOV23-050', '353c2c0e-4dd6-4fbd-bbc4-7c797bf625c6', 3, 30, 'weekly', null),
  ('NOV23-062', '353c2c0e-4dd6-4fbd-bbc4-7c797bf625c6', 3, 40, 'weekly', null),
  -- Van (Kemu) - the west, Thu (13)
  ('C-002', '353c2c0e-4dd6-4fbd-bbc4-7c797bf625c6', 4, 140, 'weekly', null),
  ('C-007', '353c2c0e-4dd6-4fbd-bbc4-7c797bf625c6', 4, 150, 'fortnightly', null),
  ('C-009', '353c2c0e-4dd6-4fbd-bbc4-7c797bf625c6', 4, 160, 'weekly', null),
  ('C-003', '353c2c0e-4dd6-4fbd-bbc4-7c797bf625c6', 4, 170, 'weekly', null),
  ('NOV23-030', '353c2c0e-4dd6-4fbd-bbc4-7c797bf625c6', 4, 180, 'weekly', null),
  ('NOV23-040', '353c2c0e-4dd6-4fbd-bbc4-7c797bf625c6', 4, 190, 'weekly', null),
  ('NOV23-041', '353c2c0e-4dd6-4fbd-bbc4-7c797bf625c6', 4, 200, 'weekly', null),
  ('NOV23-053', '353c2c0e-4dd6-4fbd-bbc4-7c797bf625c6', 4, 210, 'weekly', null),
  ('C-006', '353c2c0e-4dd6-4fbd-bbc4-7c797bf625c6', 4, 220, 'weekly', null),
  ('NOV23-062', '353c2c0e-4dd6-4fbd-bbc4-7c797bf625c6', 4, 230, 'weekly', null),
  ('NOV23-072', '353c2c0e-4dd6-4fbd-bbc4-7c797bf625c6', 4, 240, 'weekly', null),
  ('C-001', '353c2c0e-4dd6-4fbd-bbc4-7c797bf625c6', 4, 250, 'weekly', null),
  ('C-005', '353c2c0e-4dd6-4fbd-bbc4-7c797bf625c6', 4, 260, 'weekly', null),
  -- Van (Kemu) - the west, Fri (5)
  ('NOV23-006', '353c2c0e-4dd6-4fbd-bbc4-7c797bf625c6', 5, 10, 'weekly', null),
  ('NOV23-007', '353c2c0e-4dd6-4fbd-bbc4-7c797bf625c6', 5, 20, 'weekly', null),
  ('NOV23-050', '353c2c0e-4dd6-4fbd-bbc4-7c797bf625c6', 5, 30, 'weekly', null),
  ('NOV23-062', '353c2c0e-4dd6-4fbd-bbc4-7c797bf625c6', 5, 40, 'weekly', null),
  ('NOV23-068', '353c2c0e-4dd6-4fbd-bbc4-7c797bf625c6', 5, 50, 'weekly', null),
  -- Van (Kemu) - the west, Sat (1)
  ('NOV23-041', '353c2c0e-4dd6-4fbd-bbc4-7c797bf625c6', 6, 10, 'weekly', null),
  -- Darren's Van - city, inner east and south, Mon (15)
  ('NOV23-001', 'c4d95005-1007-4e0f-8c12-95cf3d727e83', 1, 10, 'weekly', null),
  ('NOV23-005', 'c4d95005-1007-4e0f-8c12-95cf3d727e83', 1, 20, 'on_call', null),
  ('NOV23-011', 'c4d95005-1007-4e0f-8c12-95cf3d727e83', 1, 30, 'weekly', null),
  ('NOV23-014', 'c4d95005-1007-4e0f-8c12-95cf3d727e83', 1, 40, 'weekly', null),
  ('NOV23-018', 'c4d95005-1007-4e0f-8c12-95cf3d727e83', 1, 50, 'weekly', null),
  ('NOV23-021', 'c4d95005-1007-4e0f-8c12-95cf3d727e83', 1, 60, 'weekly', null),
  ('NOV23-026', 'c4d95005-1007-4e0f-8c12-95cf3d727e83', 1, 70, 'weekly', null),
  ('NOV23-038', 'c4d95005-1007-4e0f-8c12-95cf3d727e83', 1, 80, 'weekly', null),
  ('NOV23-044', 'c4d95005-1007-4e0f-8c12-95cf3d727e83', 1, 90, 'weekly', null),
  ('NOV23-045', 'c4d95005-1007-4e0f-8c12-95cf3d727e83', 1, 100, 'weekly', null),
  ('NOV23-046', 'c4d95005-1007-4e0f-8c12-95cf3d727e83', 1, 110, 'on_call', null),
  ('NOV23-051', 'c4d95005-1007-4e0f-8c12-95cf3d727e83', 1, 120, 'weekly', null),
  ('NOV23-058', 'c4d95005-1007-4e0f-8c12-95cf3d727e83', 1, 130, 'weekly', null),
  ('NOV23-070', 'c4d95005-1007-4e0f-8c12-95cf3d727e83', 1, 140, 'weekly', null),
  ('NOV23-071', 'c4d95005-1007-4e0f-8c12-95cf3d727e83', 1, 150, 'weekly', null),
  -- Darren's Van - city, inner east and south, Tue (23)
  ('NOV23-001', 'c4d95005-1007-4e0f-8c12-95cf3d727e83', 2, 10, 'weekly', null),
  ('NOV23-013', 'c4d95005-1007-4e0f-8c12-95cf3d727e83', 2, 20, 'weekly', null),
  ('NOV23-015', 'c4d95005-1007-4e0f-8c12-95cf3d727e83', 2, 30, 'weekly', null),
  ('NOV23-018', 'c4d95005-1007-4e0f-8c12-95cf3d727e83', 2, 40, 'weekly', null),
  ('NOV23-019', 'c4d95005-1007-4e0f-8c12-95cf3d727e83', 2, 50, 'weekly', null),
  ('NOV23-021', 'c4d95005-1007-4e0f-8c12-95cf3d727e83', 2, 60, 'weekly', null),
  ('NOV23-023', 'c4d95005-1007-4e0f-8c12-95cf3d727e83', 2, 70, 'weekly', null),
  ('NOV23-026', 'c4d95005-1007-4e0f-8c12-95cf3d727e83', 2, 80, 'weekly', null),
  ('NOV23-037', 'c4d95005-1007-4e0f-8c12-95cf3d727e83', 2, 90, 'weekly', null),
  ('NOV23-039', 'c4d95005-1007-4e0f-8c12-95cf3d727e83', 2, 100, 'weekly', null),
  ('NOV23-043', 'c4d95005-1007-4e0f-8c12-95cf3d727e83', 2, 110, 'weekly', null),
  ('NOV23-044', 'c4d95005-1007-4e0f-8c12-95cf3d727e83', 2, 120, 'weekly', null),
  ('NOV23-048', 'c4d95005-1007-4e0f-8c12-95cf3d727e83', 2, 130, 'fortnightly', null),
  ('NOV23-049', 'c4d95005-1007-4e0f-8c12-95cf3d727e83', 2, 140, 'fortnightly', null),
  ('NOV23-051', 'c4d95005-1007-4e0f-8c12-95cf3d727e83', 2, 150, 'weekly', null),
  ('NOV23-052', 'c4d95005-1007-4e0f-8c12-95cf3d727e83', 2, 160, 'weekly', null),
  ('NOV23-058', 'c4d95005-1007-4e0f-8c12-95cf3d727e83', 2, 170, 'weekly', null),
  ('NOV23-064', 'c4d95005-1007-4e0f-8c12-95cf3d727e83', 2, 180, 'weekly', null),
  ('NOV23-066', 'c4d95005-1007-4e0f-8c12-95cf3d727e83', 2, 190, 'weekly', null),
  ('NOV23-069', 'c4d95005-1007-4e0f-8c12-95cf3d727e83', 2, 200, 'weekly', null),
  ('NOV23-070', 'c4d95005-1007-4e0f-8c12-95cf3d727e83', 2, 210, 'weekly', null),
  ('NOV23-071', 'c4d95005-1007-4e0f-8c12-95cf3d727e83', 2, 220, 'weekly', null),
  ('NOV23-077', 'c4d95005-1007-4e0f-8c12-95cf3d727e83', 2, 230, 'weekly', null),
  -- Darren's Van - city, inner east and south, Wed (13)
  ('NOV23-001', 'c4d95005-1007-4e0f-8c12-95cf3d727e83', 3, 10, 'weekly', null),
  ('NOV23-011', 'c4d95005-1007-4e0f-8c12-95cf3d727e83', 3, 20, 'weekly', null),
  ('NOV23-014', 'c4d95005-1007-4e0f-8c12-95cf3d727e83', 3, 30, 'weekly', null),
  ('NOV23-018', 'c4d95005-1007-4e0f-8c12-95cf3d727e83', 3, 40, 'weekly', null),
  ('NOV23-021', 'c4d95005-1007-4e0f-8c12-95cf3d727e83', 3, 50, 'weekly', null),
  ('NOV23-026', 'c4d95005-1007-4e0f-8c12-95cf3d727e83', 3, 60, 'weekly', null),
  ('NOV23-038', 'c4d95005-1007-4e0f-8c12-95cf3d727e83', 3, 70, 'weekly', null),
  ('NOV23-044', 'c4d95005-1007-4e0f-8c12-95cf3d727e83', 3, 80, 'weekly', null),
  ('NOV23-045', 'c4d95005-1007-4e0f-8c12-95cf3d727e83', 3, 90, 'weekly', null),
  ('NOV23-051', 'c4d95005-1007-4e0f-8c12-95cf3d727e83', 3, 100, 'weekly', null),
  ('NOV23-058', 'c4d95005-1007-4e0f-8c12-95cf3d727e83', 3, 110, 'weekly', null),
  ('NOV23-070', 'c4d95005-1007-4e0f-8c12-95cf3d727e83', 3, 120, 'weekly', null),
  ('NOV23-071', 'c4d95005-1007-4e0f-8c12-95cf3d727e83', 3, 130, 'weekly', null),
  -- Darren's Van - city, inner east and south, Thu (21)
  ('NOV23-001', 'c4d95005-1007-4e0f-8c12-95cf3d727e83', 4, 10, 'weekly', null),
  ('NOV23-015', 'c4d95005-1007-4e0f-8c12-95cf3d727e83', 4, 20, 'weekly', null),
  ('NOV23-018', 'c4d95005-1007-4e0f-8c12-95cf3d727e83', 4, 30, 'weekly', null),
  ('NOV23-021', 'c4d95005-1007-4e0f-8c12-95cf3d727e83', 4, 40, 'weekly', null),
  ('NOV23-024', 'c4d95005-1007-4e0f-8c12-95cf3d727e83', 4, 50, 'weekly', null),
  ('NOV23-025', 'c4d95005-1007-4e0f-8c12-95cf3d727e83', 4, 60, 'weekly', null),
  ('NOV23-026', 'c4d95005-1007-4e0f-8c12-95cf3d727e83', 4, 70, 'weekly', null),
  ('NOV23-039', 'c4d95005-1007-4e0f-8c12-95cf3d727e83', 4, 80, 'weekly', null),
  ('NOV23-043', 'c4d95005-1007-4e0f-8c12-95cf3d727e83', 4, 90, 'weekly', null),
  ('NOV23-044', 'c4d95005-1007-4e0f-8c12-95cf3d727e83', 4, 100, 'weekly', null),
  ('NOV23-047', 'c4d95005-1007-4e0f-8c12-95cf3d727e83', 4, 110, 'weekly', null),
  ('NOV23-051', 'c4d95005-1007-4e0f-8c12-95cf3d727e83', 4, 120, 'weekly', null),
  ('NOV23-052', 'c4d95005-1007-4e0f-8c12-95cf3d727e83', 4, 130, 'weekly', null),
  ('NOV23-058', 'c4d95005-1007-4e0f-8c12-95cf3d727e83', 4, 140, 'weekly', null),
  ('NOV23-060', 'c4d95005-1007-4e0f-8c12-95cf3d727e83', 4, 150, 'monthly_nth', 1),
  ('NOV23-064', 'c4d95005-1007-4e0f-8c12-95cf3d727e83', 4, 160, 'weekly', null),
  ('NOV23-066', 'c4d95005-1007-4e0f-8c12-95cf3d727e83', 4, 170, 'weekly', null),
  ('NOV23-069', 'c4d95005-1007-4e0f-8c12-95cf3d727e83', 4, 180, 'weekly', null),
  ('NOV23-070', 'c4d95005-1007-4e0f-8c12-95cf3d727e83', 4, 190, 'weekly', null),
  ('NOV23-071', 'c4d95005-1007-4e0f-8c12-95cf3d727e83', 4, 200, 'weekly', null),
  ('NOV23-077', 'c4d95005-1007-4e0f-8c12-95cf3d727e83', 4, 210, 'weekly', null),
  -- Darren's Van - city, inner east and south, Fri (16)
  ('NOV23-001', 'c4d95005-1007-4e0f-8c12-95cf3d727e83', 5, 10, 'weekly', null),
  ('NOV23-013', 'c4d95005-1007-4e0f-8c12-95cf3d727e83', 5, 20, 'weekly', null),
  ('NOV23-014', 'c4d95005-1007-4e0f-8c12-95cf3d727e83', 5, 30, 'weekly', null),
  ('NOV23-018', 'c4d95005-1007-4e0f-8c12-95cf3d727e83', 5, 40, 'weekly', null),
  ('NOV23-019', 'c4d95005-1007-4e0f-8c12-95cf3d727e83', 5, 50, 'weekly', null),
  ('NOV23-021', 'c4d95005-1007-4e0f-8c12-95cf3d727e83', 5, 60, 'weekly', null),
  ('NOV23-022', 'c4d95005-1007-4e0f-8c12-95cf3d727e83', 5, 70, 'weekly', null),
  ('NOV23-026', 'c4d95005-1007-4e0f-8c12-95cf3d727e83', 5, 80, 'weekly', null),
  ('NOV23-037', 'c4d95005-1007-4e0f-8c12-95cf3d727e83', 5, 90, 'weekly', null),
  ('NOV23-038', 'c4d95005-1007-4e0f-8c12-95cf3d727e83', 5, 100, 'weekly', null),
  ('NOV23-044', 'c4d95005-1007-4e0f-8c12-95cf3d727e83', 5, 110, 'weekly', null),
  ('NOV23-045', 'c4d95005-1007-4e0f-8c12-95cf3d727e83', 5, 120, 'weekly', null),
  ('NOV23-051', 'c4d95005-1007-4e0f-8c12-95cf3d727e83', 5, 130, 'weekly', null),
  ('NOV23-058', 'c4d95005-1007-4e0f-8c12-95cf3d727e83', 5, 140, 'weekly', null),
  ('NOV23-070', 'c4d95005-1007-4e0f-8c12-95cf3d727e83', 5, 150, 'weekly', null),
  ('NOV23-071', 'c4d95005-1007-4e0f-8c12-95cf3d727e83', 5, 160, 'weekly', null),
  -- Darren's Van - city, inner east and south, Sat (11)
  ('NOV23-001', 'c4d95005-1007-4e0f-8c12-95cf3d727e83', 6, 10, 'weekly', null),
  ('NOV23-014', 'c4d95005-1007-4e0f-8c12-95cf3d727e83', 6, 20, 'weekly', null),
  ('NOV23-018', 'c4d95005-1007-4e0f-8c12-95cf3d727e83', 6, 30, 'weekly', null),
  ('NOV23-021', 'c4d95005-1007-4e0f-8c12-95cf3d727e83', 6, 40, 'weekly', null),
  ('NOV23-026', 'c4d95005-1007-4e0f-8c12-95cf3d727e83', 6, 50, 'weekly', null),
  ('NOV23-044', 'c4d95005-1007-4e0f-8c12-95cf3d727e83', 6, 60, 'weekly', null),
  ('NOV23-051', 'c4d95005-1007-4e0f-8c12-95cf3d727e83', 6, 70, 'weekly', null),
  ('NOV23-058', 'c4d95005-1007-4e0f-8c12-95cf3d727e83', 6, 80, 'weekly', null),
  ('NOV23-069', 'c4d95005-1007-4e0f-8c12-95cf3d727e83', 6, 90, 'weekly', null),
  ('NOV23-070', 'c4d95005-1007-4e0f-8c12-95cf3d727e83', 6, 100, 'weekly', null),
  ('NOV23-071', 'c4d95005-1007-4e0f-8c12-95cf3d727e83', 6, 110, 'weekly', null),
  -- Werribee (Keith) - Werribee and Wyndham, Mon (2)
  ('NOV23-035', '479a4d47-8acd-4f24-89fa-305f7e364611', 1, 10, 'weekly', null),
  ('NOV23-073', '479a4d47-8acd-4f24-89fa-305f7e364611', 1, 20, 'weekly', null),
  -- Werribee (Keith) - Werribee and Wyndham, Fri (7)
  ('NOV23-017', '479a4d47-8acd-4f24-89fa-305f7e364611', 5, 10, 'monthly_nth', 1),
  ('NOV23-057', '479a4d47-8acd-4f24-89fa-305f7e364611', 5, 20, 'weekly', null),
  ('NOV23-059', '479a4d47-8acd-4f24-89fa-305f7e364611', 5, 30, 'weekly', null),
  ('NOV23-063', '479a4d47-8acd-4f24-89fa-305f7e364611', 5, 40, 'fortnightly', null),
  ('NOV23-067', '479a4d47-8acd-4f24-89fa-305f7e364611', 5, 50, 'weekly', null),
  ('NOV23-073', '479a4d47-8acd-4f24-89fa-305f7e364611', 5, 60, 'weekly', null),
  ('NOV23-078', '479a4d47-8acd-4f24-89fa-305f7e364611', 5, 70, 'weekly', null),
  -- Truck (Binod) - Geelong, Wed (7)
  ('NOV23-016', '6d18cfa0-6c82-4687-856b-4d186f6ed99c', 3, 10, 'weekly', null),
  ('NOV23-027', '6d18cfa0-6c82-4687-856b-4d186f6ed99c', 3, 20, 'weekly', null),
  ('NOV23-028', '6d18cfa0-6c82-4687-856b-4d186f6ed99c', 3, 30, 'weekly', null),
  ('NOV23-032', '6d18cfa0-6c82-4687-856b-4d186f6ed99c', 3, 40, 'weekly', null),
  ('NOV23-033', '6d18cfa0-6c82-4687-856b-4d186f6ed99c', 3, 50, 'weekly', null),
  ('NOV23-056', '6d18cfa0-6c82-4687-856b-4d186f6ed99c', 3, 60, 'weekly', null),
  ('NOV23-061', '6d18cfa0-6c82-4687-856b-4d186f6ed99c', 3, 70, 'weekly', null)
       ) as v(ref, route_id, weekday, seq, frequency, nth_of_month)
  join public.customers c
    on c.business_id = 'b7d18d8b-aa7c-4dd8-a37a-4ced75748239' and c.external_ref = v.ref
 where not exists (
   select 1 from public.route_stops x
    where x.route_id = v.route_id::uuid and x.weekday = v.weekday
      and x.customer_id = c.id and x.visit_no = 1 and x.active_to is null);
